cmake: do not require zlib if not building engine or nacl game code, do not build minizip when building game code
NaCl game compilation still needs zlib:

pnacl_deps/lib/libpng16.a: error: undefined reference to 'deflateInit2_'
pnacl_deps/lib/libpng16.a: error: undefined reference to 'deflateReset'
pnacl_deps/lib/libpng16.a: error: undefined reference to 'deflate'
pnacl_deps/lib/libpng16.a: error: undefined reference to 'deflateEnd'
pnacl_deps/lib/libpng16.a: error: undefined reference to 'inflateReset2'
pnacl_deps/lib/libpng16.a: error: undefined reference to 'adler32'
pnacl_deps/lib/libpng16.a: error: undefined reference to 'crc32'
pnacl_deps/lib/libfreetype.a: error: undefined reference to 'inflateReset'
pnacl_deps/lib/libfreetype.a: error: undefined reference to 'inflateEnd'
pnacl_deps/lib/libfreetype.a: error: undefined reference to 'inflate'
pnacl_deps/lib/libfreetype.a: error: undefined reference to 'inflateInit2_'